name: Python
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Show python version
        run: python --version
      - name: Install prerequisites
        run: |
          pip install requests
          pip install selenium
          pip install geckodriver-autoinstaller
      - name: Get desktop rewards
        run: python Python/get_rewards.py -e ${{ secrets.email }} -p ${{ secrets.password }} -r 1 -d
      - name: Get mobile rewards
        run: python Python/get_rewards.py -e ${{ secrets.email }} -p ${{ secrets.password }} -r 1 -m -d
      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: /tmp/*.png
          retention-days: 1 
      
